//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseLibrary.ModelLibrary.EntityFrameworkLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrolment
    {
        public long ID { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> EffectedDate { get; set; }
        public string LicenseType { get; set; }
        public byte[] Photo { get; set; }
        public byte[] RightThumb { get; set; }
        public byte[] RightIndex { get; set; }
        public byte[] LeftThumb { get; set; }
        public byte[] LeftIndex { get; set; }
        public Nullable<long> Branch { get; set; }
    
        public virtual Branch Branch1 { get; set; }
    }
}
