//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34011.
// 
#pragma warning disable 1591

namespace License.Test.LicenseService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ThirdPartyServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ThirdPartyService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RetrieveCardDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCardSerialNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCountofRecordsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFullDataWithIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListofDataWithSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListofDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertFineOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveFinesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ThirdPartyService() {
            this.Url = global::License.Test.Properties.Settings.Default.License_Test_LicenseService_ThirdPartyService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RetrieveCardDetailsCompletedEventHandler RetrieveCardDetailsCompleted;
        
        /// <remarks/>
        public event GetCardSerialNumberCompletedEventHandler GetCardSerialNumberCompleted;
        
        /// <remarks/>
        public event AuthenticateUserCompletedEventHandler AuthenticateUserCompleted;
        
        /// <remarks/>
        public event SaveDataCompletedEventHandler SaveDataCompleted;
        
        /// <remarks/>
        public event EditDataCompletedEventHandler EditDataCompleted;
        
        /// <remarks/>
        public event GetCountofRecordsCompletedEventHandler GetCountofRecordsCompleted;
        
        /// <remarks/>
        public event GetFullDataWithIDCompletedEventHandler GetFullDataWithIDCompleted;
        
        /// <remarks/>
        public event GetListofDataWithSearchCompletedEventHandler GetListofDataWithSearchCompleted;
        
        /// <remarks/>
        public event GetListofDataCompletedEventHandler GetListofDataCompleted;
        
        /// <remarks/>
        public event UpdateStatusCompletedEventHandler UpdateStatusCompleted;
        
        /// <remarks/>
        public event InsertFineCompletedEventHandler InsertFineCompleted;
        
        /// <remarks/>
        public event RetrieveFinesCompletedEventHandler RetrieveFinesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveCardDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardDetails RetrieveCardDetails(string cardNumber) {
            object[] results = this.Invoke("RetrieveCardDetails", new object[] {
                        cardNumber});
            return ((CardDetails)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveCardDetailsAsync(string cardNumber) {
            this.RetrieveCardDetailsAsync(cardNumber, null);
        }
        
        /// <remarks/>
        public void RetrieveCardDetailsAsync(string cardNumber, object userState) {
            if ((this.RetrieveCardDetailsOperationCompleted == null)) {
                this.RetrieveCardDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveCardDetailsOperationCompleted);
            }
            this.InvokeAsync("RetrieveCardDetails", new object[] {
                        cardNumber}, this.RetrieveCardDetailsOperationCompleted, userState);
        }
        
        private void OnRetrieveCardDetailsOperationCompleted(object arg) {
            if ((this.RetrieveCardDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveCardDetailsCompleted(this, new RetrieveCardDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCardSerialNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardDetails GetCardSerialNumber(string loggedInUsername) {
            object[] results = this.Invoke("GetCardSerialNumber", new object[] {
                        loggedInUsername});
            return ((CardDetails)(results[0]));
        }
        
        /// <remarks/>
        public void GetCardSerialNumberAsync(string loggedInUsername) {
            this.GetCardSerialNumberAsync(loggedInUsername, null);
        }
        
        /// <remarks/>
        public void GetCardSerialNumberAsync(string loggedInUsername, object userState) {
            if ((this.GetCardSerialNumberOperationCompleted == null)) {
                this.GetCardSerialNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCardSerialNumberOperationCompleted);
            }
            this.InvokeAsync("GetCardSerialNumber", new object[] {
                        loggedInUsername}, this.GetCardSerialNumberOperationCompleted, userState);
        }
        
        private void OnGetCardSerialNumberOperationCompleted(object arg) {
            if ((this.GetCardSerialNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCardSerialNumberCompleted(this, new GetCardSerialNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AuthenticateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserDetails AuthenticateUser(string key, string key_pd) {
            object[] results = this.Invoke("AuthenticateUser", new object[] {
                        key,
                        key_pd});
            return ((UserDetails)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(string key, string key_pd) {
            this.AuthenticateUserAsync(key, key_pd, null);
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(string key, string key_pd, object userState) {
            if ((this.AuthenticateUserOperationCompleted == null)) {
                this.AuthenticateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateUserOperationCompleted);
            }
            this.InvokeAsync("AuthenticateUser", new object[] {
                        key,
                        key_pd}, this.AuthenticateUserOperationCompleted, userState);
        }
        
        private void OnAuthenticateUserOperationCompleted(object arg) {
            if ((this.AuthenticateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateUserCompleted(this, new AuthenticateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response SaveData(EnrolmentModel enrolmentData) {
            object[] results = this.Invoke("SaveData", new object[] {
                        enrolmentData});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void SaveDataAsync(EnrolmentModel enrolmentData) {
            this.SaveDataAsync(enrolmentData, null);
        }
        
        /// <remarks/>
        public void SaveDataAsync(EnrolmentModel enrolmentData, object userState) {
            if ((this.SaveDataOperationCompleted == null)) {
                this.SaveDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveDataOperationCompleted);
            }
            this.InvokeAsync("SaveData", new object[] {
                        enrolmentData}, this.SaveDataOperationCompleted, userState);
        }
        
        private void OnSaveDataOperationCompleted(object arg) {
            if ((this.SaveDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveDataCompleted(this, new SaveDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response EditData(EnrolmentModel enrolmentData) {
            object[] results = this.Invoke("EditData", new object[] {
                        enrolmentData});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void EditDataAsync(EnrolmentModel enrolmentData) {
            this.EditDataAsync(enrolmentData, null);
        }
        
        /// <remarks/>
        public void EditDataAsync(EnrolmentModel enrolmentData, object userState) {
            if ((this.EditDataOperationCompleted == null)) {
                this.EditDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditDataOperationCompleted);
            }
            this.InvokeAsync("EditData", new object[] {
                        enrolmentData}, this.EditDataOperationCompleted, userState);
        }
        
        private void OnEditDataOperationCompleted(object arg) {
            if ((this.EditDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditDataCompleted(this, new EditDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCountofRecords", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetCountofRecords(string loggedInUsername) {
            object[] results = this.Invoke("GetCountofRecords", new object[] {
                        loggedInUsername});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void GetCountofRecordsAsync(string loggedInUsername) {
            this.GetCountofRecordsAsync(loggedInUsername, null);
        }
        
        /// <remarks/>
        public void GetCountofRecordsAsync(string loggedInUsername, object userState) {
            if ((this.GetCountofRecordsOperationCompleted == null)) {
                this.GetCountofRecordsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCountofRecordsOperationCompleted);
            }
            this.InvokeAsync("GetCountofRecords", new object[] {
                        loggedInUsername}, this.GetCountofRecordsOperationCompleted, userState);
        }
        
        private void OnGetCountofRecordsOperationCompleted(object arg) {
            if ((this.GetCountofRecordsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCountofRecordsCompleted(this, new GetCountofRecordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFullDataWithID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardAccountRequest GetFullDataWithID(long ID) {
            object[] results = this.Invoke("GetFullDataWithID", new object[] {
                        ID});
            return ((CardAccountRequest)(results[0]));
        }
        
        /// <remarks/>
        public void GetFullDataWithIDAsync(long ID) {
            this.GetFullDataWithIDAsync(ID, null);
        }
        
        /// <remarks/>
        public void GetFullDataWithIDAsync(long ID, object userState) {
            if ((this.GetFullDataWithIDOperationCompleted == null)) {
                this.GetFullDataWithIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFullDataWithIDOperationCompleted);
            }
            this.InvokeAsync("GetFullDataWithID", new object[] {
                        ID}, this.GetFullDataWithIDOperationCompleted, userState);
        }
        
        private void OnGetFullDataWithIDOperationCompleted(object arg) {
            if ((this.GetFullDataWithIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFullDataWithIDCompleted(this, new GetFullDataWithIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListofDataWithSearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardAccountRequestModel[] GetListofDataWithSearch(string name, string fileNo, string licenseNo, string loggedInUsername) {
            object[] results = this.Invoke("GetListofDataWithSearch", new object[] {
                        name,
                        fileNo,
                        licenseNo,
                        loggedInUsername});
            return ((CardAccountRequestModel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListofDataWithSearchAsync(string name, string fileNo, string licenseNo, string loggedInUsername) {
            this.GetListofDataWithSearchAsync(name, fileNo, licenseNo, loggedInUsername, null);
        }
        
        /// <remarks/>
        public void GetListofDataWithSearchAsync(string name, string fileNo, string licenseNo, string loggedInUsername, object userState) {
            if ((this.GetListofDataWithSearchOperationCompleted == null)) {
                this.GetListofDataWithSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListofDataWithSearchOperationCompleted);
            }
            this.InvokeAsync("GetListofDataWithSearch", new object[] {
                        name,
                        fileNo,
                        licenseNo,
                        loggedInUsername}, this.GetListofDataWithSearchOperationCompleted, userState);
        }
        
        private void OnGetListofDataWithSearchOperationCompleted(object arg) {
            if ((this.GetListofDataWithSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListofDataWithSearchCompleted(this, new GetListofDataWithSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListofData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardAccountRequestModel[] GetListofData(string loggedInUsername) {
            object[] results = this.Invoke("GetListofData", new object[] {
                        loggedInUsername});
            return ((CardAccountRequestModel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListofDataAsync(string loggedInUsername) {
            this.GetListofDataAsync(loggedInUsername, null);
        }
        
        /// <remarks/>
        public void GetListofDataAsync(string loggedInUsername, object userState) {
            if ((this.GetListofDataOperationCompleted == null)) {
                this.GetListofDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListofDataOperationCompleted);
            }
            this.InvokeAsync("GetListofData", new object[] {
                        loggedInUsername}, this.GetListofDataOperationCompleted, userState);
        }
        
        private void OnGetListofDataOperationCompleted(object arg) {
            if ((this.GetListofDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListofDataCompleted(this, new GetListofDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateStatus(string cardSerialNumber, string licenseNumber, int printStatus, string userPrinting, string printedName) {
            object[] results = this.Invoke("UpdateStatus", new object[] {
                        cardSerialNumber,
                        licenseNumber,
                        printStatus,
                        userPrinting,
                        printedName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateStatusAsync(string cardSerialNumber, string licenseNumber, int printStatus, string userPrinting, string printedName) {
            this.UpdateStatusAsync(cardSerialNumber, licenseNumber, printStatus, userPrinting, printedName, null);
        }
        
        /// <remarks/>
        public void UpdateStatusAsync(string cardSerialNumber, string licenseNumber, int printStatus, string userPrinting, string printedName, object userState) {
            if ((this.UpdateStatusOperationCompleted == null)) {
                this.UpdateStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateStatus", new object[] {
                        cardSerialNumber,
                        licenseNumber,
                        printStatus,
                        userPrinting,
                        printedName}, this.UpdateStatusOperationCompleted, userState);
        }
        
        private void OnUpdateStatusOperationCompleted(object arg) {
            if ((this.UpdateStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateStatusCompleted(this, new UpdateStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertFine", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response InsertFine(string licenseID, string details) {
            object[] results = this.Invoke("InsertFine", new object[] {
                        licenseID,
                        details});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void InsertFineAsync(string licenseID, string details) {
            this.InsertFineAsync(licenseID, details, null);
        }
        
        /// <remarks/>
        public void InsertFineAsync(string licenseID, string details, object userState) {
            if ((this.InsertFineOperationCompleted == null)) {
                this.InsertFineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertFineOperationCompleted);
            }
            this.InvokeAsync("InsertFine", new object[] {
                        licenseID,
                        details}, this.InsertFineOperationCompleted, userState);
        }
        
        private void OnInsertFineOperationCompleted(object arg) {
            if ((this.InsertFineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertFineCompleted(this, new InsertFineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveFines", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Fine[] RetrieveFines(string licenseID) {
            object[] results = this.Invoke("RetrieveFines", new object[] {
                        licenseID});
            return ((Fine[])(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveFinesAsync(string licenseID) {
            this.RetrieveFinesAsync(licenseID, null);
        }
        
        /// <remarks/>
        public void RetrieveFinesAsync(string licenseID, object userState) {
            if ((this.RetrieveFinesOperationCompleted == null)) {
                this.RetrieveFinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveFinesOperationCompleted);
            }
            this.InvokeAsync("RetrieveFines", new object[] {
                        licenseID}, this.RetrieveFinesOperationCompleted, userState);
        }
        
        private void OnRetrieveFinesOperationCompleted(object arg) {
            if ((this.RetrieveFinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveFinesCompleted(this, new RetrieveFinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CardDetails {
        
        private long idField;
        
        private string cardNumberField;
        
        private bool issuedField;
        
        private string dateUploadedField;
        
        private long branchIDField;
        
        private string branchField;
        
        private string responseField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool Issued {
            get {
                return this.issuedField;
            }
            set {
                this.issuedField = value;
            }
        }
        
        /// <remarks/>
        public string DateUploaded {
            get {
                return this.dateUploadedField;
            }
            set {
                this.dateUploadedField = value;
            }
        }
        
        /// <remarks/>
        public long BranchID {
            get {
                return this.branchIDField;
            }
            set {
                this.branchIDField = value;
            }
        }
        
        /// <remarks/>
        public string Branch {
            get {
                return this.branchField;
            }
            set {
                this.branchField = value;
            }
        }
        
        /// <remarks/>
        public string response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Fine {
        
        private long idField;
        
        private string licenseIDField;
        
        private string detailsField;
        
        private System.Nullable<System.DateTime> dateField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseID {
            get {
                return this.licenseIDField;
            }
            set {
                this.licenseIDField = value;
            }
        }
        
        /// <remarks/>
        public string Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CardAccountRequestModel {
        
        private long idField;
        
        private string licenseIDField;
        
        private string cardSerialNumberField;
        
        private string lastnameField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string nameOnCardField;
        
        private string dateOfBirthField;
        
        private string maritalStatusField;
        
        private string sexField;
        
        private string religionField;
        
        private string mothersMaidenNameField;
        
        private string nationalityField;
        
        private string utilityBillField;
        
        private string iDNumberField;
        
        private string localGovernmentAreaField;
        
        private string bloodGroupField;
        
        private string licenseTypeField;
        
        private string issueDateField;
        
        private string validTillDateField;
        
        private string fileNumberField;
        
        private string emailAddressField;
        
        private string phoneNumberField;
        
        private string addressField;
        
        private string userPrintingField;
        
        private int printStatusField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseID {
            get {
                return this.licenseIDField;
            }
            set {
                this.licenseIDField = value;
            }
        }
        
        /// <remarks/>
        public string CardSerialNumber {
            get {
                return this.cardSerialNumberField;
            }
            set {
                this.cardSerialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string NameOnCard {
            get {
                return this.nameOnCardField;
            }
            set {
                this.nameOnCardField = value;
            }
        }
        
        /// <remarks/>
        public string DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string MaritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string Religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
            }
        }
        
        /// <remarks/>
        public string MothersMaidenName {
            get {
                return this.mothersMaidenNameField;
            }
            set {
                this.mothersMaidenNameField = value;
            }
        }
        
        /// <remarks/>
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        public string UtilityBill {
            get {
                return this.utilityBillField;
            }
            set {
                this.utilityBillField = value;
            }
        }
        
        /// <remarks/>
        public string IDNumber {
            get {
                return this.iDNumberField;
            }
            set {
                this.iDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LocalGovernmentArea {
            get {
                return this.localGovernmentAreaField;
            }
            set {
                this.localGovernmentAreaField = value;
            }
        }
        
        /// <remarks/>
        public string BloodGroup {
            get {
                return this.bloodGroupField;
            }
            set {
                this.bloodGroupField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseType {
            get {
                return this.licenseTypeField;
            }
            set {
                this.licenseTypeField = value;
            }
        }
        
        /// <remarks/>
        public string IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        public string ValidTillDate {
            get {
                return this.validTillDateField;
            }
            set {
                this.validTillDateField = value;
            }
        }
        
        /// <remarks/>
        public string FileNumber {
            get {
                return this.fileNumberField;
            }
            set {
                this.fileNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string UserPrinting {
            get {
                return this.userPrintingField;
            }
            set {
                this.userPrintingField = value;
            }
        }
        
        /// <remarks/>
        public int PrintStatus {
            get {
                return this.printStatusField;
            }
            set {
                this.printStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CardAccountRequest {
        
        private long idField;
        
        private string licenseIDField;
        
        private string cardSerialNumberField;
        
        private string hashedCardSerialNumberField;
        
        private string lastnameField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string nameOnCardField;
        
        private string printedNameField;
        
        private string dateOfBirthField;
        
        private string maritalStatusField;
        
        private string sexField;
        
        private string religionField;
        
        private string mothersMaidenNameField;
        
        private string nationalityField;
        
        private string utilityBillField;
        
        private string iDNumberField;
        
        private string localGovernmentAreaField;
        
        private string bloodGroupField;
        
        private string licenseTypeField;
        
        private string issueDateField;
        
        private string validTillDateField;
        
        private string fileNumberField;
        
        private string emailAddressField;
        
        private string phoneNumberField;
        
        private string addressField;
        
        private byte[] photoField;
        
        private string fingerIdLeftField;
        
        private byte[] fingerPrintLeftField;
        
        private string fingerIdRightField;
        
        private byte[] fingerPrintRightField;
        
        private System.Nullable<int> printStatusField;
        
        private string userPrintingField;
        
        private System.Nullable<System.DateTime> dateEnroledField;
        
        private System.Nullable<System.DateTime> datePrintedField;
        
        private System.Nullable<long> branchIDField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseID {
            get {
                return this.licenseIDField;
            }
            set {
                this.licenseIDField = value;
            }
        }
        
        /// <remarks/>
        public string CardSerialNumber {
            get {
                return this.cardSerialNumberField;
            }
            set {
                this.cardSerialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string HashedCardSerialNumber {
            get {
                return this.hashedCardSerialNumberField;
            }
            set {
                this.hashedCardSerialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string NameOnCard {
            get {
                return this.nameOnCardField;
            }
            set {
                this.nameOnCardField = value;
            }
        }
        
        /// <remarks/>
        public string PrintedName {
            get {
                return this.printedNameField;
            }
            set {
                this.printedNameField = value;
            }
        }
        
        /// <remarks/>
        public string DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string MaritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string Religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
            }
        }
        
        /// <remarks/>
        public string MothersMaidenName {
            get {
                return this.mothersMaidenNameField;
            }
            set {
                this.mothersMaidenNameField = value;
            }
        }
        
        /// <remarks/>
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        public string UtilityBill {
            get {
                return this.utilityBillField;
            }
            set {
                this.utilityBillField = value;
            }
        }
        
        /// <remarks/>
        public string IDNumber {
            get {
                return this.iDNumberField;
            }
            set {
                this.iDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LocalGovernmentArea {
            get {
                return this.localGovernmentAreaField;
            }
            set {
                this.localGovernmentAreaField = value;
            }
        }
        
        /// <remarks/>
        public string BloodGroup {
            get {
                return this.bloodGroupField;
            }
            set {
                this.bloodGroupField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseType {
            get {
                return this.licenseTypeField;
            }
            set {
                this.licenseTypeField = value;
            }
        }
        
        /// <remarks/>
        public string IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        public string ValidTillDate {
            get {
                return this.validTillDateField;
            }
            set {
                this.validTillDateField = value;
            }
        }
        
        /// <remarks/>
        public string FileNumber {
            get {
                return this.fileNumberField;
            }
            set {
                this.fileNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
            }
        }
        
        /// <remarks/>
        public string FingerIdLeft {
            get {
                return this.fingerIdLeftField;
            }
            set {
                this.fingerIdLeftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FingerPrintLeft {
            get {
                return this.fingerPrintLeftField;
            }
            set {
                this.fingerPrintLeftField = value;
            }
        }
        
        /// <remarks/>
        public string FingerIdRight {
            get {
                return this.fingerIdRightField;
            }
            set {
                this.fingerIdRightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FingerPrintRight {
            get {
                return this.fingerPrintRightField;
            }
            set {
                this.fingerPrintRightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PrintStatus {
            get {
                return this.printStatusField;
            }
            set {
                this.printStatusField = value;
            }
        }
        
        /// <remarks/>
        public string UserPrinting {
            get {
                return this.userPrintingField;
            }
            set {
                this.userPrintingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateEnroled {
            get {
                return this.dateEnroledField;
            }
            set {
                this.dateEnroledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DatePrinted {
            get {
                return this.datePrintedField;
            }
            set {
                this.datePrintedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> BranchID {
            get {
                return this.branchIDField;
            }
            set {
                this.branchIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Response {
        
        private string resultField;
        
        private long recordIDField;
        
        private string errMessageField;
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public long RecordID {
            get {
                return this.recordIDField;
            }
            set {
                this.recordIDField = value;
            }
        }
        
        /// <remarks/>
        public string ErrMessage {
            get {
                return this.errMessageField;
            }
            set {
                this.errMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EnrolmentModel {
        
        private long idField;
        
        private string lastnameField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string nameOnCardField;
        
        private string dateOfBirthField;
        
        private string maritalStatusField;
        
        private string sexField;
        
        private string religionField;
        
        private string mothersMaidenNameField;
        
        private string nationalityField;
        
        private string utilityBillField;
        
        private string iDNumberField;
        
        private string localGovernmentAreaField;
        
        private string bloodGroupField;
        
        private string licenseTypeField;
        
        private string issueDateField;
        
        private string validTillDateField;
        
        private string fileNumberField;
        
        private string emailAddressField;
        
        private string phoneNumberField;
        
        private string addressField;
        
        private byte[] photoField;
        
        private string fingerIdLeftField;
        
        private byte[] fingerPrintLeftField;
        
        private string fingerIdRightField;
        
        private byte[] fingerPrintRightField;
        
        private string userPrintingField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string NameOnCard {
            get {
                return this.nameOnCardField;
            }
            set {
                this.nameOnCardField = value;
            }
        }
        
        /// <remarks/>
        public string DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string MaritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string Religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
            }
        }
        
        /// <remarks/>
        public string MothersMaidenName {
            get {
                return this.mothersMaidenNameField;
            }
            set {
                this.mothersMaidenNameField = value;
            }
        }
        
        /// <remarks/>
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        public string UtilityBill {
            get {
                return this.utilityBillField;
            }
            set {
                this.utilityBillField = value;
            }
        }
        
        /// <remarks/>
        public string IDNumber {
            get {
                return this.iDNumberField;
            }
            set {
                this.iDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LocalGovernmentArea {
            get {
                return this.localGovernmentAreaField;
            }
            set {
                this.localGovernmentAreaField = value;
            }
        }
        
        /// <remarks/>
        public string BloodGroup {
            get {
                return this.bloodGroupField;
            }
            set {
                this.bloodGroupField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseType {
            get {
                return this.licenseTypeField;
            }
            set {
                this.licenseTypeField = value;
            }
        }
        
        /// <remarks/>
        public string IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        public string ValidTillDate {
            get {
                return this.validTillDateField;
            }
            set {
                this.validTillDateField = value;
            }
        }
        
        /// <remarks/>
        public string FileNumber {
            get {
                return this.fileNumberField;
            }
            set {
                this.fileNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
            }
        }
        
        /// <remarks/>
        public string FingerIdLeft {
            get {
                return this.fingerIdLeftField;
            }
            set {
                this.fingerIdLeftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FingerPrintLeft {
            get {
                return this.fingerPrintLeftField;
            }
            set {
                this.fingerPrintLeftField = value;
            }
        }
        
        /// <remarks/>
        public string FingerIdRight {
            get {
                return this.fingerIdRightField;
            }
            set {
                this.fingerIdRightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FingerPrintRight {
            get {
                return this.fingerPrintRightField;
            }
            set {
                this.fingerPrintRightField = value;
            }
        }
        
        /// <remarks/>
        public string UserPrinting {
            get {
                return this.userPrintingField;
            }
            set {
                this.userPrintingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FunctionModel {
        
        private string nameField;
        
        private string pageLinkField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string PageLink {
            get {
                return this.pageLinkField;
            }
            set {
                this.pageLinkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserDetails {
        
        private long idField;
        
        private string usernameField;
        
        private string roleField;
        
        private FunctionModel[] functionField;
        
        private string responseField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        public FunctionModel[] Function {
            get {
                return this.functionField;
            }
            set {
                this.functionField = value;
            }
        }
        
        /// <remarks/>
        public string Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void RetrieveCardDetailsCompletedEventHandler(object sender, RetrieveCardDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveCardDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveCardDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetCardSerialNumberCompletedEventHandler(object sender, GetCardSerialNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCardSerialNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCardSerialNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AuthenticateUserCompletedEventHandler(object sender, AuthenticateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SaveDataCompletedEventHandler(object sender, SaveDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void EditDataCompletedEventHandler(object sender, EditDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetCountofRecordsCompletedEventHandler(object sender, GetCountofRecordsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCountofRecordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCountofRecordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetFullDataWithIDCompletedEventHandler(object sender, GetFullDataWithIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFullDataWithIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFullDataWithIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardAccountRequest Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardAccountRequest)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetListofDataWithSearchCompletedEventHandler(object sender, GetListofDataWithSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListofDataWithSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListofDataWithSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardAccountRequestModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardAccountRequestModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetListofDataCompletedEventHandler(object sender, GetListofDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListofDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListofDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardAccountRequestModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardAccountRequestModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UpdateStatusCompletedEventHandler(object sender, UpdateStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void InsertFineCompletedEventHandler(object sender, InsertFineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertFineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertFineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void RetrieveFinesCompletedEventHandler(object sender, RetrieveFinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveFinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveFinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Fine[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Fine[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591